apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-sidecar-logging-config
  namespace: ecc
data:
  fluentd.conf: |
    <source>
      type tail
      format none
      path /app/ecc/sidecar-logging/logs/sidecar-*.log
      pos_file /app/ecc/sidecar-logging/logs/sidecar.log.pos
      tag sidecar.format1
    </source>

    <match **>
      @id elasticsearch-sidecar-logging
      @type elasticsearch
      @log_level info
      type_name _doc
      include_tag_key true
      host elasticsearch-logging.kube-system.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix esoff
    </match>    
